variable "vpc_id" {}
variable "public_subnet" {}
variable "private_subnet" {}
variable "key_name" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
variable "sqldbinstance" {}